Updated PorterConfig type to use verbosity instead of debug and debug…
getporter/operator pull request #114
Opened 2022-08-31 21:56 UTC by sgettys

…-plugins

Signed-off-by: Steven Gettys <s.gettys@f5.com>

2022-08-31 21:57 UTC, sgettys commented
#112 
#113

2022-08-31 21:57 UTC, sgettys commented
Closes #112 and #113

2022-09-01 16:01 UTC, carolynvs requested changes

2022-09-01 16:01 UTC, carolynvs commented on docs/content/quickstart/_index.md
> +## Environment Configuration
🎉

2022-09-02 18:00 UTC, carolynvs approved these changes
Looks great, thanks!

2022-09-02 18:00 UTC, merged